### ISSUE TITLE
Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by undelete** [alireza-saberi/secret-santa#5]
Hi, i see this error:

url.js:81
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)

**Comment by alireza-saberi** [comment]
@undelete Can you provide the following please?

## Expected behavior

## Actual behavior

## Steps to reproduce

##### Version of your NodeJS and AngularJS

##### Operating system

##### Browser

**Comment by alireza-saberi** [comment]
No detail is provided.  and there is no way to reproduce the error with the information provided.
